#
# build-mega2560.yml
# Build and push the fw to a WebDAV server
#

name: Build-Probeless

on:
  push:
    branches:
    - probeless
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'
  workflow_dispatch:
    inputs:
      name:
        description: 'Thing'
        required: false

jobs:
  build_fw:
    name: Build for mega2560

    runs-on: ubuntu-latest

    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Prague

    - name: Pull the repo
      uses: actions/checkout@v2
      with:
        ref: probeless

    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update

    - name: Run ${{ matrix.test-platform }} Build
      run: |
        pio run
        curl --user '${{ secrets.DAV_USER }}:${{ secrets.DAV_PASS }}' -T '.pio/build/mega2560/firmware.hex' "${{ secrets.DAV_SERVER }}${{ secrets.DAV_PATH }}/firmware_`date +%d_%m_%H_%M`.hex" --anyauth
